---
pagetitle: Venue
---

## Université Grenoble Alpes

Located in the heart of a **remarkable environment** with 3 mountain ranges (Belledonne, Chartreuse and Vercors), Université Grenoble Alpes is situated on several sites in the Grenoble metropolitan area (Grenoble Alpes Métropole). The main campus, located in the districts of Gières and Saint-Martin-d'Hères, is recognized as **one of the most beautiful in France**, with its 3,000 trees, cultural and sports facilities and unique architecture. 

## Getting there

**Three international airports are located less than 90 minutes from Grenoble**: Lyon Saint-Exupéry, Grenoble Alpes Isère and Geneva. In total, more than 200 direct destinations are accessible.

With up to 10 direct Grenoble-Paris round trips by high-speed TGV train, and with the Lyon Part-Dieu hub 1hr15mins away, **the rail offer from Grenoble is also very attractive**. Ideally located in the city centre, Grenoble railway station is perfectly connected to the city's bus and tram network. 

Finally, the Auvergne-Rhône-Alpes motorway network is the most densely populated area after Île-de-France. Thanks to the A41, A48, A49 and A51 motorways, **Grenoble is easily connected to Lyon, the Rhone Valley, Switzerland and Italy**.  