
## `r paste(.x,": ",.y)`

```{r}
# submissions <-
#   # read_csv("~/Desktop/CERE2025/submissions.csv") |>
#   googlesheets4::read_sheet(
#     "https://docs.google.com/spreadsheets/d/1aIncHFZ6uTmb0Lz4Wvm9um1CrNjz5W4imuCkK-F5CRs/edit?usp=drive_link",
#     col_types = "c"
#   ) |>
#   clean_names() |>
#   select(nb = docid, abstract) |>
#   mutate(nb = as.character(nb))

symposium_sessions <-
  googlesheets4::read_sheet(
    "https://docs.google.com/spreadsheets/d/19LbkLxJh2mq2LgIy9GyUScm2m5UANRYg-FwLKhAp3E4/edit?usp=sharing",
    col_types = "c"
  ) |>
  select(time, txt, Track, abstract)

parallel_sessions <-
  read_csv(here::here("assets/cere_program.csv"), col_select = c(1:6)) |>
  # googlesheets4::read_sheet(
  #   "https://docs.google.com/spreadsheets/d/1fWzjjaZC3wEy434IXi7y8IQkUarYu60JlxSBxliEfKE/edit?usp=drive_link",
  #   range = "A:F",
  #   col_types = "c"
  # ) |>
  clean_names() |>
  mutate(
    day = if_else(str_detect(cere2025_program_overview, "^[0-9]"), NA_character_, cere2025_program_overview)) |>
  fill(day, .direction = "down") |>
  drop_na(x3) |>
  mutate(txt = ifelse(str_detect(x2,"Room"), 1, 0)) |>
  mutate(txt = paste("Parallel Session", cumsum(txt))) |>
  add_row(
    cere2025_program_overview = "11.15",
    x5 = "609342 Data Workshop - Damien Dupré - Identifying Correct or Incorrect Emotion Recognition from Facial Expression Time",
    day = "Wednesday 16th July",
    txt = "Parallel Session 2"
  ) |>
  select(time = cere2025_program_overview, T1 = x2, T2 = x3, T3 = x4, T4 = x5, T5 = x6, day, txt) |>
  pivot_longer(-c(time, day, txt), names_to = "Track") |>
  filter(!str_starts(value, "Room")) |>
  mutate(
    time = ifelse(is.na(time), "title", time),
    nb = str_extract(value, "^[0-9]+"),
    value = str_remove(value, "^[0-9]+\\s*")
  )

session_track <- parallel_sessions |>
  filter(txt == .x, Track == .y)
  # filter(txt == "Parallel Session 1", Track == "T5")

session_track_coms <- session_track |>
  filter(time != "title", !str_starts(value, "Discuss"))

session_track_details <- session_track |>
  filter(time == "title") |>
  mutate(
    time = paste(min(session_track_coms$time), " - ", max(session_track_coms$time)),
    Type = value |>
      str_extract("^(Symposium|Data Workshop)") |>
      coalesce("Talks"),
    value = str_remove(value, "^(Data Workshop - |Symposium: |Symposium )")
  )
```

```{r}
#| eval: !expr 'session_track_details$Type == "Talks"'

session_track_details |>
  left_join(
    symposium_sessions |>
      filter(time == "title") |>
      select(-time),
    by = join_by(txt, Track)
  ) |>
  select(Session = txt, Track, Time = time, Type, Title = value) |>
  t() |>
  as.data.frame() |>
  rownames_to_column() |>
  kable(col.names = NULL) |> 
  column_spec(1, width = "5em") |> 
  column_spec(2, width = "40em")
```

```{r, results='asis'}
#| eval: !expr 'session_track_details$Type == "Talks"'

session_track_coms |>
  left_join(submissions, by = join_by(nb)) |>
  select(Communication = value, Time = time, Abstract = abstract) |> 
  pivot_longer(!Communication, values_to = "Abstract") |>
  filter(name == "Abstract") |>
  select(-name) |>
  mutate(
    Communication = glue::glue("__{Communication}__") |>
      str_replace_all("[*]" , ""),
    Abstract = Abstract |>
      str_replace_all("[\r\n]" , "") |>
      str_replace_all("[*]" , "")
  ) |>
  mutate(` ` = "\\") |>
  pivot_longer(everything()) |> 
  filter(value != "Discussion") |>
  mutate(
    name = if_else(value != "\\", paste0(name, ":"), name),
    jump = "\\"
  ) |>
  unite("line", 1:3, sep = " ")  |>
  unlist() |>
  cat(sep = "\n")
```

```{r}
#| eval: !expr 'session_track_details$Type == "Symposium"'

session_track_details |>
  left_join(
    symposium_sessions |>
      filter(time == "title") |>
      select(-time),
    by = join_by(txt, Track)
  ) |>
  select(Session = txt, Track, Time = time, Type, Title = value, Abstract = abstract) |>
  t() |> 
  as.data.frame() |>
  rownames_to_column() |>
  kable(col.names = NULL) |> 
  column_spec(1, width = "5em") |> 
  column_spec(2, width = "40em")
```

```{r, results='asis'}
#| eval: !expr 'session_track_details$Type == "Symposium"'
session_track_coms |>
  left_join(symposium_sessions, by = join_by(time, txt, Track)) |>
  select(Communication = value, Time = time, Abstract = abstract) |>
  pivot_longer(!Communication, values_to = "Abstract") |>
  filter(!str_starts(Communication, "Discuss"), name == "Abstract") |>
  select(-name) |>
  mutate(
    Communication = glue::glue("__{Communication}__") |>
      str_replace_all("[*]" , ""),
    Abstract = Abstract |>
      str_replace_all("[\r\n]" , "") |>
      str_replace_all("[*]" , "")
  ) |>
  mutate(` ` = "\\") |>
  pivot_longer(everything()) |>
  filter(value != "Discussion") |>
  mutate(
    name = if_else(value != "\\", paste0(name, ":"), name),
    jump = "\\"
  ) |>
  unite("line", 1:3, sep = " ")  |>
  unlist() |>
  cat(sep = "\n")
```

```{r}
#| eval: !expr 'session_track_details$Type == "Data Workshop"'

session_track_details |>
  left_join(
    symposium_sessions |>
      filter(time == "title") |>
      select(-time),
    by = join_by(txt, Track)
  ) |>
  select(Session = txt, Track, Time = time, Type, Title = value, Abstract = abstract) |>
  t() |>
  as.data.frame() |>
  rownames_to_column() |>
  kable(col.names = NULL) |> 
  column_spec(1, width = "5em") |> 
  column_spec(2, width = "40em")
```

\newpage