---
title: "Poster Session 2"
execute: 
  echo: false
  
format: 
  html:
    page-layout: full
---

Abstract available when rows are expended:

```{r}
#| include: false

# libraries --------------------------------------------------------------------
library(reactable)

# data -------------------------------------------------------------------------
source(here::here("internal/computation_posters.R"), local = knitr::knit_global())

df <- posters |>
  dplyr::filter(day == "Poster Session 2") |>
  dplyr::select(Title = title, Authors = authors, Abstract = abstract, Group = group)
```

```{r}
reactable(
  df,
  pagination = FALSE,
  highlight = TRUE,
  searchable = TRUE,
  groupBy = "Group",
  defaultExpanded = TRUE,
  columns = list(
    Group = colDef(minWidth = 200),
    Title = colDef(minWidth = 400),
    Authors = colDef(minWidth = 200),
    # Abstract = colDef(show = FALSE),
    Abstract = colDef(
      name = "",
      sortable = FALSE,
      cell = function() htmltools::tags$button("Show Abstract")
    )
  ),
  onClick = JS("function(rowInfo, column) {window.alert(rowInfo.values['Abstract'])}"),
  rowStyle = JS("function(rowInfo) {
    if (rowInfo.subRows.length) {
      return { borderBottom: '3px solid #E84E0F' }
    }
  }")
)
```
